name: Deploy Node.js app to Azure Web App

on:
  workflow_dispatch:
    inputs:
      artifactName:
        description: 'Name of the Artifact to Deploy'
        required: true
        default: 'node-app'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.inputs.artifactName }}
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Next-Whisk'
          slot-name: 'Production'
          package: .
